steps:

- name: 'gcr.io/cloud-builders/docker'
  id: Build images
  args: [ 'build',
          '-t', 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:latest',
          '-t', 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:${SHORT_SHA}',
          '.' ]

- name: 'gcr.io/cloud-builders/docker'
  id: Run tests
  args:
    - 'run'
    - '--entrypoint=sh'
    - 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:${SHORT_SHA}'
    - '-c'
    - |
        cd /deploy
        pytest --collect-only
        pytest --verbose
        RETVAL=$?
        if [ $${RETVAL} -ne 0 ]; then
          echo "tests failed"
          exit 1
        else
          echo "tests passed"
          exit 0
        fi

- name: 'gcr.io/cloud-builders/docker'
  id: Push short sha tag image to GCR
  args:
  - 'push'
  - 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:${SHORT_SHA}'

- name: 'gcr.io/cloud-builders/docker'
  id: Push latest tag image to GCR
  args:
  - 'push'
  - 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:latest'

- name: 'gcr.io/cloud-builders/gsutil'
  id: Get encrypted GitHub SSH key
  args: ['cp', 'gs://ons-blaise-${_ENV}-git-ssh-key-bucket/*' , '.']

- name: 'gcr.io/cloud-builders/gcloud'
  id: Unencrypt GitHub SSH key
  args:
    - kms
    - decrypt
    - --ciphertext-file=ssh.enc
    - --plaintext-file=/root/.ssh/id_rsa
    - --location=europe-west2
    - --keyring=git-deploy
    - --key=git-deploy
  volumes:
    - name: 'ssh'
      path: /root/.ssh

- name: 'gcr.io/cloud-builders/gcloud'
  id: Connect to GitHub
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_rsa
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_rsa
      EOF
      mv known_hosts /root/.ssh/known_hosts
  volumes:
    - name: 'ssh'
      path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  id: Clone deploy-k8s repo
  args:
    - clone
    - git@github.com:ONSdigital/blaise-deploy-k8s.git
  volumes:
    - name: 'ssh'
      path: /root/.ssh

- name: 'gcr.io/cloud-builders/gcloud'
  id: Checkout dev branch and configure user
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    cd blaise-deploy-k8s && \
    git checkout dev && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)') && \
    git config --list

- name: 'gcr.io/cloud-builders/gcloud'
  id: Create yaml from temaplate replacing image tag
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" bncm.yaml.tpl | \
     sed "s/COMMIT_SHA/${SHORT_SHA}/g" > blaise-deploy-k8s/services/blaise-nisra-case-mover-sftp/bncm.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: Commit changes back to k8s repo
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cd blaise-deploy-k8s/services/blaise-nisra-case-mover-sftp && \
    git add bncm.yaml && \
    git commit -m "Deploying blaise-nisra-case-mover-sftp:${SHORT_SHA}
    Image gcr.io/${PROJECT_ID}/blaise-nisra-case-mover-sftp:${SHORT_SHA} Built from commit ${COMMIT_SHA}
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git remote -v && \
    git push origin dev
  volumes:
    - name: 'ssh'
      path: /root/.ssh
      
images:
  - 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:${SHORT_SHA}'
  - 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:latest'
