steps:
- id: 'Build image
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:latest',
          '-t', 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:${SHORT_SHA}',
          '.' ]

# run the unit tests in the image
- id: Image Unit Tests
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'run'
    - '--entrypoint=sh'
    - 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:${SHORT_SHA}'
    - '-c'
    - |
        cd /deploy
        pytest --collect-only
        pytest --verbose
        RETVAL=$?
        if [ $${RETVAL} -ne 0 ]; then
          echo "tests failed"
          exit 1
        else
          echo "tests passed"
          exit 0
        fi

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push image to GCR
  args:
  - 'push'
  - 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:${SHORT_SHA}'

# Add latest tag to GCR
- name: 'gcr.io/cloud-builders/docker'
  id: Add latest tag to GCR
  args:
  - 'push'
  - 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:latest'


- name: 'gcr.io/cloud-builders/gsutil'
  id: Get encrypted Github ssh key
  args: ['cp', 'gs://ons-blaise-${_ENV}-git-ssh-key-bucket/*' , '.']

# SSH key needed to allow gcloud to push changes (SHORT_SHA) to other repositories
- name: 'gcr.io/cloud-builders/gcloud'
  id: Unencrypt Github ssh key
  args:
    - kms
    - decrypt
    - --ciphertext-file=ssh.enc
    - --plaintext-file=/root/.ssh/id_rsa
    - --location=europe-west2
    - --keyring=git-deploy
    - --key=git-deploy
  volumes:
    - name: 'ssh'
      path: /root/.ssh

# Set up git with key and domain
- name: 'gcr.io/cloud-builders/gcloud'
  id: Connect to Github
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_rsa
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_rsa
      EOF
      mv known_hosts /root/.ssh/known_hosts
  volumes:
    - name: 'ssh'
      path: /root/.ssh

# Connect to the repository
- name: 'gcr.io/cloud-builders/git'
  id: Clone k8s repository
  args:
    - clone
    - git@github.com:ONSdigital/blaise-deploy-k8s.git
  volumes:
    - name: 'ssh'
      path: /root/.ssh

# This step clones the blaise-nisra-case-mover-sftp-k8s repository
- name: 'gcr.io/cloud-builders/gcloud'
  id: Checkout dev branch and configure user
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    cd blaise-deploy-k8s && \
    git checkout dev && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)') && \
    git config --list

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Create yaml from temaplate with image tag
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" bncm-cronjob.yaml.tpl | \
     sed "s/COMMIT_SHA/${SHORT_SHA}/g" > blaise-deploy-k8s/services/blaise-nisra-case-mover-sftp/bncm-cronjob.yaml

# This step pushes the manifest back to blaise-nisra-case-mover-sftp-k8s
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cd blaise-deploy-k8s/services/blaise-nisra-case-mover-sftp && \
    git add bncm-cronjob.yaml && \
    git commit -m "Deploying blaise-nisra-case-mover-sftp:${SHORT_SHA}
    Image gcr.io/${PROJECT_ID}/blaise-nisra-case-mover-sftp:${SHORT_SHA} Built from commit ${COMMIT_SHA}
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git remote -v && \
    git push origin candidate
  volumes:
    - name: 'ssh'
      path: /root/.ssh
images:
  - 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:${SHORT_SHA}'
  - 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:latest'
