# This step generates the new manifest
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: Build docker image
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud builds submit --tag gcr.io/${_PROJECT_ID}/nisra-case-mover

  - name: "gcr.io/cloud-builders/gcloud"
    id: Cloud run deploy
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud run deploy \
        --image gcr.io/${_PROJECT_ID}/nisra-case-mover \
        --vpc-connector=vpcconnect \
        --vpc-egress=all \
        --region=${_REGION} \
        --cpu=2 \
        --memory=512Mi \
        --max-instances=1 \
        --set-env-vars SFTP_PORT=${_SFTP_PORT} \
        --set-env-vars SFTP_HOST=${_SFTP_HOST} \
        --set-env-vars SFTP_USERNAME=${_SFTP_USERNAME} \
        --set-env-vars SFTP_PASSWORD=${_SFTP_PASSWORD} \
        --set-env-vars SURVEY_SOURCE_PATH=${_SURVEY_SOURCE_PATH} \
        --set-env-vars INSTRUMENT_DESTINATION_PATH=${_INSTRUMENT_DESTINATION_PATH} \
        --set-env-vars INSTRUMENT_SOURCE_PATH="" \
        --set-env-vars NISRA_BUCKET_NAME=${_NISRA_BUCKET_NAME}

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Slack Notify"
    waitFor: ["Deploy service"]
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        python3 -u slack/slack-notify.py;
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'REPO_NAME=$REPO_NAME'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'SLACK_CHANNEL=$_SLACK_CHANNEL'
      - 'SLACK_WEBHOOK=$_SLACK_WEBHOOK'
