steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:latest', '.' ]
images:
- 'eu.gcr.io/$PROJECT_ID/blaise-nisra-case-mover-sftp:latest'